package ClasesInstagual;

public class Foto_de_perfil_de_usuario_de_publicacion_vista_usuario_no_registrado {
	public Publicacion__vista_usuario_no_regsitrado_ _publicacion__vista_usuario_no_regsitrado_;
	public Ver_perfil _ver_perfil;
}