package ClasesInstagual;

import java.util.Vector;
import ClasesInstagual.Publicacion__vista_usuario_registrado_;

public class Publicaciones_vista_usuario_logueado {
	public Pantalla_inicio___Usuario_registrado _pantalla_inicio___Usuario_registrado;
	public Vector<Publicacion__vista_usuario_registrado_> _publicacion__vista_usuario_registrado_ = new Vector<Publicacion__vista_usuario_registrado_>();
}